### ISSUE TITLE
"Warning: Firmware Broken" message stays there after using this plugin

### ISSUE THREAD

**Issue by tiagovaz** [RomainOdeval/OctoPrint-CrealityTemperature#5]
Any way to get rid of "Warning: Firmware Broken" message once using this plugin? Should it be managed by the plugin itself, or by Octoprint?

**Comment by RomainOdeval** [comment]
Hello,

Good question. I don't use this plugin anymore, due to printer firware update. Try to deactivate this plugin and check if temperature is displayed without.

**Comment by mkurrein** [comment]
My Ender 3 Max, 4.2.2 board and V1.0.1.06 firmware with CR Touch, produced this warning but does not have this fault.
![Image 01-01-2022 at 15 17](https://user-images.githubusercontent.com/96948522/147854484-b71f53eb-06af-48a2-af9b-ddab24dbbd01.jpg)
How then can I remove the warning?

**Comment by RomainOdeval** [comment]
Hello.

Have you tried to disable this plugin and check if temperature is displayed without ?

If not, try to use OctoPrint "update firmware plugin" first to up-to-date your printer.

**Comment by mkurrein** [comment]
Thank you!

**Comment by mkurrein** [comment]
My error, apologies, it stopped reporting temperature as soon as I started printing.  Not I’ve installed the 2X plugin it all works perfectly.
<img width="642" alt="Screen Shot 2022-01-02 at 12 06 39" src="https://user-images.githubusercontent.com/96948522/147875216-1d8a80ed-cd1b-451f-aa8a-06da6ae17e24.png">
<img width="588" alt="Screen Shot 2022-01-02 at 12 08 29" src="https://user-images.githubusercontent.com/96948522/147875240-885dc903-276a-4b4d-93a5-93004672dff8.png">

**Comment by RomainOdeval** [comment]
Yes, it seems that you have another common issue.
My plugin fix only one of two known issues. See https://community.octoprint.org/t/octoprint-doesnt-show-a-temperature-graph-for-my-creality-printer-with-stock-firmware/23901
